name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui pynput pyperclip pillow pystray

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --onefile senha_colar.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: senha-colar-exe
          path: dist/senha_colar.exe
